### ISSUE TITLE
SetParent will free node if parent is already set

### ISSUE THREAD

**Issue by skamradt** [davidberneda/GenericTree#3]
The SetParent method will call orphan, which if a parent is already set will indirectly free the node when delete is called.  Orphan should not call delete, but a different method which will remove it from the internal list but NOT free the node.   This means that your destructor must also change to call delete directly as orphan would leave a reference

**Comment by davidberneda** [comment]
Thanks for your help, Orphan no longer calls Free. Destructor already destroys node so it works fine
