### ISSUE TITLE
suggestion: Add swap or exchange node method

### ISSUE THREAD

**Issue by skamradt** [davidberneda/GenericTree#4]
The generic tree structure mostly works well, but if one wants to perform sorting, there is no way to get at and adjust the underlying node order easily.  I would suggest adding either a swap or exchange method that would simply swap positions in the internal FItems array between two child elements.

**Comment by davidberneda** [comment]
Thanks for your help, added new Exchange method to swap children nodes. Pending to add a TNode Sort method with a user-defined custom Compare callback function, to reorder nodes at any level (optionally recursive)
