### ISSUE TITLE
ForEach problem with orphan 

### ISSUE THREAD

**Issue by skamradt** [davidberneda/GenericTree#5]
If one performs an orphan as part of the forEach loop, this can cause problems as the array is resized in the middle of the ForEach call.  One example that I ran into this was by moving the entire contents of one tree to another by setting a new parent in a forEach call.

One possible solution would be to load the nodes to process into a new list separate from the fItems array so any changes in the array do not impact what needs to be run.

**Comment by skamradt** [comment]
```
// note: uses Classes;
procedure TNode<T>.ForEach(const AProc: TNodeProc; const Recursive: Boolean);
var t : TInteger;
    N : TTypeItem;
    L : TList;
begin
  L := TList.Create;
  try
    for t := 0 to count-1 do
      L.Add(fItems[t]);

    for t:=0 to L.Count-1 do
    begin
      N:=L[t];
      AProc(N);

      if Recursive then
         N.ForEach(AProc);
    end;
  finally
    L.Free;
  end;
end;
```

**Comment by davidberneda** [comment]
Yes this is a problem. A separate local list will work for Orphan, but not if a node is destroyed (on Windows).
On mobile ARC compiler the "N" variable will be set to nil, I'm adding a check before calling AProc.

I'll add the local FItems copy too

**Comment by skamradt** [comment]
Problem with checking count still causes problems if nodes are moved to another list.  Should be:

```
while t<Length(tmp) do
  begin
    N:=tmp[t];
```
